# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

 - script: |
      pip install flake8 pylint
      flake8 mypackage/  # Adjust the path to your package's source code
      pylint mypackage/  # Adjust the path to your package's source code
    displayName: 'Code Quality Analysis'

  - script: |
      pip install coverage
      coverage run -m pytest
      coverage report -m
    displayName: 'Code Coverage'

  - script: |
      pip install twine
      python setup.py sdist bdist_wheel
      twine upload dist/*
    displayName: 'Publish to PyPI'
    condition: succeeded()  # Only publish if previous steps succeed